version: '3.8'

services:
  db:
    image: postgres:17
    container_name: fqr_proj_postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: fqr_proj_api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env.example
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "src"]

volumes:
  postgres_data:
