version: '3.8'

services:
  db:
    image: postgres:17
    container_name: fqr_proj_postgresdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  redis:
    image: redis:7-alpine
    container_name: fqr_proj_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  api:
    container_name: fqr_proj_api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src  # Mount source code for hot reloading
    #command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "src"] 
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "src", "--reload"] # dev

volumes:
  postgres_data:
  redis_data:
